# Copyright (c) 2022 Konnexions GmbH. All rights reserved. Use of this
# source code is governed by the Konnexions Public License (KX-PL)
# Version 2020.05, that can be found in the LICENSE file.

"""Stub file."""
import sqlalchemy
from sqlalchemy import Integer

class Version:
    version_id: int
    version_version: str
    def __init__(self, _row_id: int = ..., version: str = ...) -> None:
        self._exist = None
        ...
    def _get_columns(self) -> None: ...
    @classmethod
    def create_dbt(cls) -> None: ...
    def exists(self) -> bool: ...
    def finalise(self) -> None: ...
    @classmethod
    def from_id(cls, id_version: int) -> Version: ...
    @classmethod
    def from_row(cls, row: sqlalchemy.engine.Row) -> Version: ...
    def get_columns_in_tuple(self) -> tuple[int | Integer, str]: ...
    def persist_2_db(self) -> None: ...
    @classmethod
    def select_version_version_unique(cls) -> str: ...
