"""Library Stub."""
from typing import List

def create_db_trigger_created_at(table_name: str) -> None: ...
def create_db_trigger_function(column_name: str) -> None: ...
def create_db_trigger_modified_at(table_name: str) -> None: ...
def create_db_triggers(table_names: List[str]) -> None: ...
def create_schema() -> None: ...
