"""Library Stub."""

def connect_db() -> None: ...
def connect_db_admin() -> None: ...
def create_database() -> None: ...
def create_database_postgresql() -> None: ...
def disconnect_db() -> None: ...
def drop_database() -> None: ...
def drop_database_postgresql() -> None: ...
def prepare_connect_db() -> None: ...
def prepare_connect_db_admin() -> None: ...
def upgrade_database() -> None: ...
def upgrade_database_version() -> None: ...
