[tool.bandit]

[tool.black]
line-length = 79

[tool.isort]
force_single_line = true
overwrite_in_place = true
profile = "black"

[tool.mypy]
check_untyped_defs = true
disallow_any_decorated = true
disallow_any_explicit = true
disallow_any_expr = false
disallow_any_generics = true
disallow_any_unimported = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
follow_imports = "skip"
namespace_packages = true
no_implicit_optional = true
pretty = true
show_column_numbers = true
show_error_codes = true
strict = true
strict_equality = true
warn_no_return = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

[tool.pydocstyle]

[tool.pylint]
disable = ["C0330", "C0326"]

[tool.pytest.ini_options]
console_output_style = "count"
log_auto_indent = true
log_cli = true
log_level = "DEBUG"
testpaths = "tests"
