[tool.bandit]
skips = ["B404", "B603", "B607", "B608"]

[tool.black]
line-length = 120

[tool.isort]
float_to_top = true
force_single_line = true
overwrite_in_place = true
profile = "black"

[tool.mypy]
check_untyped_defs = true
disallow_any_decorated = true
disallow_any_explicit = true
disallow_any_expr = false
disallow_any_generics = true
disallow_any_unimported = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
follow_imports = "skip"
namespace_packages = false
no_implicit_optional = true
plugins = "sqlmypy"
pretty = true
show_column_numbers = true
show_error_codes = true
strict = true
strict_equality = true
warn_no_return = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

[[tool.pydoc-markdown.loaders]]
search_path = [ "src/dcr" ]
type = "python"

[tool.pydoc-markdown.renderer]
content_directory_name = "docs"
output_directory = "."
type = "mkdocs"

[[tool.pydoc-markdown.renderer.pages]]
contents = [ "dcr.*" ]
name = "index"
title = "API Documentation"

[tool.pydocstyle]
match='((?!test_).*\.py)((?!TET).*\.py)'

[tool.pytest.ini_options]
console_output_style = "count"
markers = ["issue"]
norecursedirs = "./tests/helpers"
pythonpath = "./src/dcr/"
testpaths = "./tests/"
