"""Library stub."""
import psycopg2

def connect_db_admin() -> psycopg2.connection: ...
def create_database() -> None: ...
def create_database_postgresql() -> None: ...
def disconnect_db_admin(conn: psycopg2.connection, cur: psycopg2.cursor) -> None: ...
def drop_database() -> None: ...
def drop_database_postgresql() -> None: ...
def upgrade_database() -> None: ...
def upgrade_database_version() -> None: ...
