"""Library stub."""
import psycopg2
from psycopg2.extensions import connection
from psycopg2.extensions import cursor

def connect_db() -> connection: ...
def connect_db_admin() -> connection: ...
def create_database() -> None: ...
def create_database_postgresql() -> None: ...
def disconnect_db(conn: connection, cur: cursor) -> None: ...
def drop_database() -> None: ...
def drop_database_postgresql() -> None: ...
def prepare_connect_db_admin() -> None: ...
def select_version_version_unique(cur: cursor) -> str: ...
def upgrade_database() -> None: ...
def upgrade_database_version(cur: cursor) -> None: ...
