"""Library Stub."""
from pathlib import Path
from typing import Dict
from typing import List

import libs.cfg
import sqlalchemy.orm

def connect_db() -> None: ...
def create_db_trigger_function(column_name: str) -> None: ...
def create_db_trigger_created_at(table_name: str) -> None: ...
def create_db_trigger_modified_at(table_name: str) -> None: ...
def create_db_triggers(table_names: List[str]) -> None: ...
def create_dbt_content(table_name: str) -> None: ...
def create_dbt_document(table_name: str) -> None: ...
def create_dbt_journal(table_name: str) -> None: ...
def create_dbt_language(table_name: str) -> None: ...
def create_dbt_run(table_name: str) -> None: ...
def create_dbt_version(
    table_name: str,
) -> None: ...
def create_schema() -> None: ...
def disconnect_db() -> None: ...
def insert_dbt_row(
    table_name: str,
    columns: libs.cfg.Columns,
) -> sqlalchemy.Integer: ...
def insert_journal(
    document_id: sqlalchemy.Integer,
    journal_action: str,
) -> None: ...
def load_db_data_from_json(initial_database_data: Path) -> None: ...
def prepare_connect_db() -> None: ...
def select_document_file_name_sha256(
    document_id: sqlalchemy.Integer, sha256: str
) -> str | None: ...
def select_run_run_id_last() -> int | sqlalchemy.Integer: ...
def select_version_version_unique() -> str: ...
def update_dbt_id(
    table_name: str,
    id_where: sqlalchemy.Integer,
    columns: Dict[str, str],
) -> None: ...
