"""Library stub."""

import logging

import sqlalchemy.orm
from libs import cfg

def check_db_up_to_date(logger: logging.Logger) -> None: ...
def create_database(logger: logging.Logger) -> None: ...
def create_or_upgrade_database(logger: logging.Logger) -> None: ...
def create_table_document() -> None: ...
def create_table_journal() -> None: ...
def create_table_run() -> None: ...
def create_table_run_entry() -> None: ...
def create_table_version() -> sqlalchemy.Table: ...
def select_version_unique(logger: logging.Logger) -> str: ...
def insert_table(
    logger: logging.Logger, table: str, columns: cfg.Columns
) -> sqlalchemy.Integer: ...

# TBD
# def upgrade_database(logger: logging.Logger) -> None: ...
