"""Library stub."""

import pathlib
from typing import Callable

def check_and_create_directories() -> None: ...
def convert_pdf_2_image() -> None: ...
def convert_pdf_2_image_file() -> None: ...
def create_directory(directory_type: str, directory_name: str) -> None: ...
def prepare_pdf() -> None: ...
def prepare_pdf_for_tesseract() -> None: ...
def process_inbox_accepted(
    update_document_status: Callable[[str, str, str, str], None],
    target_file_name: str,
) -> None: ...
def process_inbox_rejected(
    update_document_status: Callable[[str, str, str, str], None],
) -> None: ...
def initialise_document_inbox(file: pathlib.Path) -> None: ...
def process_inbox_files() -> None: ...
def process_inbox_pandoc() -> None: ...
