"""Library stub."""

import logging

def check_and_create_inboxes(logger: logging.Logger) -> None: ...
def create_directory(
    logger: logging.Logger, directory_type: str, directory_name: str
) -> None: ...
def process_inbox_new(logger: logging.Logger) -> None: ...
def process_input_new_pandoc(logger: logging.Logger) -> None: ...
def process_input_new_pdf(logger: logging.Logger) -> None: ...
