"""Library Stub."""
import pathlib
import typing

import db.cfg
import sqlalchemy.engine

def check_directories() -> None: ...
def compute_sha256(file: pathlib.Path) -> str: ...
def delete_auxiliary_file(file_name: str) -> None: ...
def finalize_file_processing() -> int: ...
def prepare_document_4_next_step(next_file_type: str, next_step: str) -> None: ...
def prepare_file_names(
    file_extension: str = db.cfg.DOCUMENT_FILE_TYPE_PDF,
) -> typing.Tuple[str, str]: ...
def progress_msg(msg: str) -> None: ...
def progress_msg_connected() -> None: ...
def progress_msg_core(msg: str) -> None: ...
def progress_msg_disconnected() -> None: ...
def progress_msg_empty_before(msg: str) -> None: ...
def reset_statistics_language() -> None: ...
def reset_statistics_total() -> None: ...
def show_statistics_language() -> None: ...
def show_statistics_total() -> None: ...
def start_document_processing(document: sqlalchemy.engine.Row) -> None: ...
def terminate_fatal(error_msg: str) -> None: ...
