"""Library Stub."""
import pathlib

from sqlalchemy import Table
from sqlalchemy import engine
from sqlalchemy.engine import Connection
from sqlalchemy.engine import Row

def check_directories() -> None: ...
def get_sha256(file: pathlib.Path) -> str: ...
def initialise_document_child(journal_action: str) -> None: ...
def progress_msg(msg: str) -> None: ...
def progress_msg_connected() -> None: ...
def progress_msg_disconnected() -> None: ...
def progress_msg_empty_before(msg: str) -> None: ...
def select_documents(conn: Connection, dbt: Table, next_step: str) -> engine.CursorResult: ...
def start_document_processing(document: Row, journal_action: str) -> None: ...
def str_2_path(param: str) -> pathlib.Path: ...
def terminate_fatal(error_msg: str) -> None: ...
