# Copyright (c) 2022 Konnexions GmbH. All rights reserved. Use of this
# source code is governed by the Konnexions Public License (KX-PL)
# Version 2020.05, that can be found in the LICENSE file.

"""Module stub file."""

def parse_tetml() -> None: ...
def parse_tetml_file_line() -> None: ...
def parse_tetml_file_word() -> None: ...
