"""Library Stub."""
from typing import Dict
from typing import List

import spacy.tokens
import sqlalchemy

def get_text_from_page_lines(page_data: Dict[str, str | List[Dict[str, int | str]]]) -> str: ...
def get_token_attributes(token: spacy.tokens.Token) -> Dict[str, bool | float | int | str]: ...
def tokenize() -> None: ...
def tokenize_document(nlp: spacy.Language, dbt_content: sqlalchemy.Table) -> None: ...
