# Copyright (c) 2022 Konnexions GmbH. All rights reserved. Use of this
# source code is governed by the Konnexions Public License (KX-PL)
# Version 2020.05, that can be found in the LICENSE file.

"""Module stub file."""
import pathlib

import dcr.db.cls_action

def check_and_create_directories() -> None: ...
def create_directory(directory_type: str, directory_name: str) -> None: ...
def initialise_action(
    action_code: str = ...,
    directory_name: str = ...,
    directory_type: str = ...,
    file_name: str = ...,
    id_parent: int = ...,
) -> dcr.db.cls_action.Action: ...
def initialise_base(file_path: pathlib.Path) -> None: ...
def prepare_pdf(file: pathlib.Path) -> None: ...
def process_inbox() -> None: ...
def process_inbox_accepted(next_step: str) -> None: ...
def process_inbox_file(file_path: pathlib.Path) -> None: ...
def process_inbox_language() -> None: ...
def process_inbox_rejected(error_code: str, error: str) -> None: ...
