"""Library Stub."""
import typing

def debug_xml_element_all(
    event: str, parent_tag: str, attrib: typing.Dict[str, str], text: typing.Iterable[str | None]
) -> None: ...
def debug_xml_element_text() -> None: ...
def init_parse_result_sentence_trext() -> None: ...
def insert_content_tetml_line() -> None: ...
def insert_content_tetml_word() -> None: ...
def parse_tag_box(parent_tag: str, parent: typing.Iterable[str]) -> None: ...
def parse_tag_content(parent_tag: str, parent: typing.Iterable[str]) -> None: ...
def parse_tag_doc_info(parent_tag: str, parent: typing.Iterable[str]) -> None: ...
def parse_tag_document(parent_tag: str, parent: typing.Iterable[str]) -> None: ...
def parse_tag_line(parent_tag: str, parent: typing.Iterable[str]) -> None: ...
def parse_tag_page(parent_tag: str, parent: typing.Iterable[str]) -> None: ...
def parse_tag_pages(parent_tag: str, parent: typing.Iterable[str]) -> None: ...
def parse_tag_para(parent_tag: str, parent: typing.Iterable[str]) -> None: ...
def parse_tag_text(parent_tag: str, parent: typing.Iterable[str]) -> None: ...
def parse_tag_word(parent_tag: str, parent: typing.Iterable[str]) -> None: ...
def parse_tetml() -> None: ...
def parse_tetml_file_line() -> None: ...
def parse_tetml_file_word() -> None: ...
