"""Library stub."""

import logging
import sys

def get_args(logger: logging.Logger, argv: sys.argv) -> dict[str, bool]: ...
def get_config(logger: logging.Logger) -> None: ...
def initialise_logger() -> logging.Logger: ...
def main() -> None: ...
