"""Library stub."""

import logging
from typing import List

def get_args(logger: logging.Logger, argv: List[str]) -> dict[str, bool]: ...
def get_config(logger: logging.Logger) -> None: ...
def initialise_logger() -> logging.Logger: ...
def main(argv: List[str]) -> None: ...
