# -*- coding: utf-8 -*-

"""Library Stub."""

DCR_ARGV_0: str

def check_db_up_to_date() -> None: ...
def get_args(argv: list[str]) -> dict[str, bool]: ...
def initialise_logger() -> None: ...
def load_data_from_dbt_language() -> None: ...
def main(argv: list[str]) -> None: ...
def process_convert_image_2_pdf() -> None: ...
def process_convert_non_pdf_2_pdf() -> None: ...
def process_convert_pdf_2_image() -> None: ...
def process_documents(args: dict[str, bool]) -> None: ...
def process_export_lt_rules() -> None: ...
def process_extract_text_from_pdf() -> None: ...
def process_inbox_directory() -> None: ...
def process_store_parse_result_in_json() -> None: ...
def process_tokenize() -> None: ...
