"""Library Stub."""
import os
import pathlib
from typing import Tuple

import cfg.glob
import sqlalchemy.engine

def check_directories() -> None: ...
def compute_sha256(file: pathlib.Path) -> str: ...
def delete_auxiliary_file(file_name: str) -> None: ...
def finalize_file_processing() -> int: ...
def get_file_type(file_name: pathlib.Path | str | None) -> str | None: ...
def get_pdf_pages_no(
    file_name: str,
) -> int: ...
def get_stem_name(file_name: pathlib.Path | str | None) -> str | None: ...
def prepare_document_4_next_step(next_file_type: str, next_step: str) -> None: ...
def prepare_file_names(
    file_extension: str,
) -> Tuple[str, str]: ...
def progress_msg(msg: str) -> None: ...
def progress_msg_connected() -> None: ...
def progress_msg_core(msg: str) -> None: ...
def progress_msg_disconnected() -> None: ...
def progress_msg_empty_before(msg: str) -> None: ...
def progress_msg_line_type(msg: str) -> None: ...
def reset_statistics_total() -> None: ...
def show_statistics_language() -> None: ...
def show_statistics_total() -> None: ...
def start_document_processing(document: sqlalchemy.engine.Row) -> None: ...
def terminate_fatal(error_msg: str) -> None: ...
def terminate_fatal_setup(error_msg: str) -> None: ...
