"""Library Stub."""
import pathlib

def compute_sha256(file: pathlib.Path | str) -> str: ...
def delete_auxiliary_file(file_name: pathlib.Path | str) -> None: ...
def get_file_type(file_name: pathlib.Path | str | None) -> str: ...
def get_full_name(directory_name: pathlib.Path | str | None, file_name: pathlib.Path | str | None) -> str: ...
def get_os_independent_name(name: pathlib.Path | str | None) -> str: ...
def get_path_name(name: pathlib.Path | str | None) -> pathlib.Path | str: ...
def get_pdf_pages_no(
    file_name: pathlib.Path | str,
) -> int: ...
def get_stem_name(file_name: pathlib.Path | str | None) -> str: ...
def progress_msg(msg: str) -> None: ...
def progress_msg_connected(database: str | None, user: str | None) -> None: ...
def progress_msg_core(msg: str) -> None: ...
def progress_msg_disconnected() -> None: ...
def progress_msg_empty_before(msg: str) -> None: ...
def progress_msg_line_type(msg: str) -> None: ...
def reset_statistics_total() -> None: ...
def show_statistics_language() -> None: ...
def show_statistics_total() -> None: ...
def terminate_fatal(error_msg: str) -> None: ...
def terminate_fatal_setup(error_msg: str) -> None: ...
