"""Library Stub."""

import pathlib

def check_and_create_directories() -> None: ...
def create_directory(directory_type: str, directory_name: str) -> None: ...
def initialise_document_base(file: pathlib.Path) -> None: ...
def prepare_document_base(file: pathlib.Path) -> None: ...
def prepare_document_child_accepted() -> None: ...
def prepare_pdf(file: pathlib.Path) -> None: ...
def process_inbox() -> None: ...
def process_inbox_accepted(next_step: str, journal_action: str) -> None: ...
def process_inbox_file(file: pathlib.Path) -> None: ...
def process_inbox_rejected(error_code: str, journal_action: str) -> None: ...
