name: Continuous Integration

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

jobs:
  development:
    name: "OS ${{ matrix.os }} - Python ${{ matrix.python-version }} - Development"
    runs-on: "${{ matrix.os }}"
#   env:
    strategy:
      matrix:
# TBD
#       os: ["ubuntu-20.04", "windows-latest"]
        os: ["ubuntu-20.04"]
# TBD
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: "actions/checkout@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install pip"
        run: "make pip"
      - name: "Install pipenv"
        run: "make pipenv"
      - name: "Install dcr dependencies"
        run: "make pipenv_dev"
      - name: "Run Bandit for finding common security issues"
        run: |
          pipenv run pip freeze | grep bandit
          make bandit
      - name: "Run Flake8 for style guide enforcement"
        run: |
          pipenv run pip freeze | grep flake8
          make flake8
# TBD
#      - name: "Run MyPy for static typing"
#        run: |
#          pipenv run pip freeze | grep mypy
#          make mypy
# TBD
#      - name: "Run PyLint for checking for errors in Python code"
#        run: |
#          pipenv run pip freeze | grep pylint
#          make pylint
      - name: "Run pydocstyle for docstring style enforcement"
        run: |
          pipenv run pip freeze | grep pydocstyle
          make pydocstyle
      - name: "Run Radon for computing various code metrics"
        run: |
          pipenv run pip freeze | grep radon
          make radon
# TBD
#      - name: "Run pytest for writing better program"
#        run: |
#          pipenv run pip freeze | grep pytest
#          make pytest

  production:
    name: "OS ${{ matrix.os }} - Python ${{ matrix.python-version }} - Production"
    runs-on: "${{ matrix.os }}"
    #   env:
    strategy:
      matrix:
        os: ["ubuntu-20.04", "windows-latest"]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: "actions/checkout@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install pip"
        run: "make pip"
      - name: "Install pipenv"
        run: "make pipenv"
      - name: "Install dcr dependencies"
        run: "make pipenv_prod"
      - name: "Compile the Python code"
        run: "make compileall"
