"""Library Stub."""

def check_exists_object(
    is_line_type_table: bool = False,
    is_text_parser: bool = False,
) -> None: ...
def progress_msg(is_verbose: bool, msg: str) -> None: ...
def progress_msg_core(msg: str) -> None: ...
def terminate_fatal(error_msg: str) -> None: ...
